services:
  - type: web
    name: list-n-ez
    runtime: node
    buildCommand: cd server && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false